### PR TITLE
DISTPG-897 Documented install from tarball steps for PG server

### PR DESCRIPTION
**Pull request by nastena1606**

### CODE REVIEW

**Review by shahidullah79 — APPROVED** [review]
steps looks fine to me.

**Review by maqeel75 — APPROVED** [review]
LGTM

**Review by Naeem-Akhter — APPROVED** [review]
LGTM.

**Comment by shahidullah79** [comment]
In the document, in component details section the name should be 'percona-etcd' instead of 'etcd'

**Review by shahidullah79 — APPROVED** [review]
LGTM

**Review by maqeel75 — APPROVED** [review]
LGTM

**Pull request merged**
