### PR TITLE
PG-229 Doc. Fixed query syntax in pg_stat_monitor example;

### PR DESCRIPTION
**Pull request by nastena1606**
Fixed link to the user guide
modified:   docs/pg-stat-monitor.md

### CODE REVIEW

**Review by patrickbirch — APPROVED** [review]
LGTM

**Review by Naeem-Akhter — COMMENTED** [review]
I would suggest following query: 

SELECT DISTINCT userid::regrole, pg_stat_monitor.datname, substr(query,0, 50) AS query, calls, bucket, bucket_start_time, queryid,  client_ip
  FROM pg_stat_monitor, pg_database
  WHERE pg_database.oid = oid;

**Review by patrickbirch — APPROVED** [review]
LGTM

**Review by Naeem-Akhter — APPROVED** [review]
Looks good!

**Pull request merged**
